version: '3'
services:
  homeassistant:
    container_name: homeassistant
    image: "ghcr.io/home-assistant/home-assistant:2023.2"
    volumes:
      - './homeassistant/config:/config'
      - /etc/localtime:/etc/localtime:ro
    devices:
      # Passing through Zigbee receiver into Docker container
      - /dev/ttyACM0:/dev/ttyUSB0
    restart: unless-stopped
    privileged: false
    network_mode: host
  pihole:
    container_name: pihole
    image: pihole/pihole:2023.01.10
    ports:
      - "53:53/tcp"
      - "53:53/udp"
      - "80:80/tcp"
    environment:
      TZ: 'America/Detroit'
    dns:
      # Specify Quad9 DNS server to fix DNS issues while updating adlists ("Update Gravity")
      - 9.9.9.9
    env_file:
      - pihole.env
    volumes:
      - './pihole/etc-pihole:/etc/pihole'
      - './pihole/etc-dnsmasq.d:/etc/dnsmasq.d'
    restart: unless-stopped
  tailscale:
    container_name: tailscale
    image: tailscale/tailscale
    volumes:
      - './tailscale/var-lib:/var/lib'
      - './tailscale/dev-net-tun:/dev/net/tun'
    network_mode: host
    environment:
      - TS_NO_LOGS_NO_SUPPORT=true
      - TS_ACCEPT_DNS=false
    env_file:
      - tailscale.env
